In [18]:
import pandas as pd

In [19]:
df = pd.read_json("../data/raw/complaints.json")

In [20]:
df.head()

,_index,_type,_id,_score,_source
0,complaint-public-v2,complaint,3211475,0,"{'tags': None, 'zip_code': '90301', 'complaint..."
1,complaint-public-v2,complaint,3229299,0,"{'tags': 'Servicemember', 'zip_code': '319XX',..."
2,complaint-public-v2,complaint,3199379,0,"{'tags': None, 'zip_code': '77069', 'complaint..."
3,complaint-public-v2,complaint,2673060,0,"{'tags': None, 'zip_code': '48066', 'complaint..."
4,complaint-public-v2,complaint,3203545,0,"{'tags': None, 'zip_code': '10473', 'complaint..."

In [21]:
df.columns

Index(['_index', '_type', '_id', '_score', '_source'], dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78313 entries, 0 to 78312
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   _index   78313 non-null  object
 1   _type    78313 non-null  object
 2   _id      78313 non-null  int64
 3   _score   78313 non-null  int64
 4   _source  78313 non-null  object
dtypes: int64(2), object(3)
memory usage: 3.0+ MB

In [23]:
df.head(10)

,_index,_type,_id,_score,_source
0,complaint-public-v2,complaint,3211475,0,"{'tags': None, 'zip_code': '90301', 'complaint..."
1,complaint-public-v2,complaint,3229299,0,"{'tags': 'Servicemember', 'zip_code': '319XX',..."
2,complaint-public-v2,complaint,3199379,0,"{'tags': None, 'zip_code': '77069', 'complaint..."
3,complaint-public-v2,complaint,2673060,0,"{'tags': None, 'zip_code': '48066', 'complaint..."
4,complaint-public-v2,complaint,3203545,0,"{'tags': None, 'zip_code': '10473', 'complaint..."
5,complaint-public-v2,complaint,3275312,0,"{'tags': 'Older American', 'zip_code': '48227'..."
6,complaint-public-v2,complaint,3238804,0,"{'tags': None, 'zip_code': '76262', 'complaint..."
7,complaint-public-v2,complaint,3249272,0,"{'tags': None, 'zip_code': '07753', 'complaint..."
8,complaint-public-v2,complaint,3351653,0,"{'tags': None, 'zip_code': '60621', 'complaint..."
9,complaint-public-v2,complaint,3273612,0,"{'tags': None, 'zip_code': '99354', 'complaint..."

In [24]:
df = pd.json_normalize(df["_source"])

In [25]:
df.head()

,tags,zip_code,complaint_id,issue,date_received,state,consumer_disputed,product,company_response,company,submitted_via,date_sent_to_company,company_public_response,sub_product,timely,complaint_what_happened,sub_issue,consumer_consent_provided
0,None,90301,3211475,Attempts to collect debt not owed,2019-04-13T12:00:00-05:00,CA,N/A,Debt collection,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-04-13T12:00:00-05:00,None,Credit card debt,Yes,,Debt is not yours,Consent not provided
1,Servicemember,319XX,3229299,Written notification about debt,2019-05-01T12:00:00-05:00,GA,N/A,Debt collection,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-05-01T12:00:00-05:00,None,Credit card debt,Yes,Good morning my name is XXXX XXXX and I apprec...,Didn't receive enough information to verify debt,Consent provided
2,None,77069,3199379,"Other features, terms, or problems",2019-04-02T12:00:00-05:00,TX,N/A,Credit card or prepaid card,Closed with explanation,JPMORGAN CHASE & CO.,Web,2019-04-02T12:00:00-05:00,None,General-purpose credit card or charge card,Yes,I upgraded my XXXX XXXX card in XX/XX/2018 and...,Problem with rewards from credit card,Consent provided
3,None,48066,2673060,Trouble during payment process,2017-09-13T12:00:00-05:00,MI,N/A,Mortgage,Closed with explanation,JPMORGAN CHASE & CO.,Web,2017-09-14T12:00:00-05:00,None,Conventional home mortgage,Yes,,None,Consent not provided
4,None,10473,3203545,Fees or interest,2019-04-05T12:00:00-05:00,NY,N/A,Credit card or prepaid card,Closed with explanation,JPMORGAN CHASE & CO.,Referral,2019-04-05T12:00:00-05:00,None,General-purpose credit card or charge card,Yes,,Charged too much interest,N/A

In [26]:
df.columns

Index(['tags', 'zip_code', 'complaint_id', 'issue', 'date_received', 'state',
       'consumer_disputed', 'product', 'company_response', 'company',
       'submitted_via', 'date_sent_to_company', 'company_public_response',
       'sub_product', 'timely', 'complaint_what_happened', 'sub_issue',
       'consumer_consent_provided'],
      dtype='object')

In [27]:
df = df[["complaint_what_happened", "issue"]]

In [28]:
df.head()

,complaint_what_happened,issue
0,,Attempts to collect debt not owed
1,Good morning my name is XXXX XXXX and I apprec...,Written notification about debt
2,I upgraded my XXXX XXXX card in XX/XX/2018 and...,"Other features, terms, or problems"
3,,Trouble during payment process
4,,Fees or interest

In [29]:
df = df.rename(columns={
    "complaint_what_happened": "text",
    "issue": "label"
})

In [30]:
df.head()

,text,label
0,,Attempts to collect debt not owed
1,Good morning my name is XXXX XXXX and I apprec...,Written notification about debt
2,I upgraded my XXXX XXXX card in XX/XX/2018 and...,"Other features, terms, or problems"
3,,Trouble during payment process
4,,Fees or interest

In [31]:
df.head()

,text,label
0,,Attempts to collect debt not owed
1,Good morning my name is XXXX XXXX and I apprec...,Written notification about debt
2,I upgraded my XXXX XXXX card in XX/XX/2018 and...,"Other features, terms, or problems"
3,,Trouble during payment process
4,,Fees or interest

In [32]:
df["text"].isnull().sum()

np.int64(0)

In [33]:
df = df[df["text"].str.strip() != ""]

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21072 entries, 1 to 78312
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    21072 non-null  object
 1   label   21072 non-null  object
dtypes: object(2)
memory usage: 493.9+ KB

In [35]:
df = df.drop_duplicates()

In [36]:
df.shape

(20932, 2)

In [37]:
df["text"] = df["text"].str.lower()

In [38]:
df["text"] = df["text"].str.replace(r"[^a-zA-Z0-9\s]", "", regex=True)

In [39]:
df["text"] = df["text"].str.replace(r"\s+", " ", regex=True).str.strip()

In [40]:
df.head()

,text,label
1,good morning my name is xxxx xxxx and i apprec...,Written notification about debt
2,i upgraded my xxxx xxxx card in xxxx2018 and w...,"Other features, terms, or problems"
10,chase card was reported on xxxx2019 however fr...,Incorrect information on your report
11,on xxxx2018 while trying to book a xxxx xxxx t...,Incorrect information on your report
14,my grand son give me check for 160000 i deposi...,Managing an account

In [41]:
df["label"].value_counts()

label
Managing an account                                2269
Problem with a purchase shown on your statement    1802
Incorrect information on your report               1167
Other features, terms, or problems                  752
Closing an account                                  745
                                                   ...
Problem with an overdraft                             1
Unauthorized transactions/trans. issues               1
Fees                                                  1
Adding money                                          1
Problem with overdraft                                1
Name: count, Length: 133, dtype: int64

In [42]:
label_counts = df["label"].value_counts()

valid_labels = label_counts[label_counts >= 100].index

df = df[df["label"].isin(valid_labels)]

In [43]:
df["label"].value_counts()

label
Managing an account                                                                 2269
Problem with a purchase shown on your statement                                     1802
Incorrect information on your report                                                1167
Other features, terms, or problems                                                   752
Closing an account                                                                   745
Loan servicing, payments, escrow account                                             654
Problem with a lender or other company charging your account                         584
Loan modification,collection,foreclosure                                             582
Trouble during payment process                                                       526
Closing your account                                                                 524
Account opening, closing, or management                                              520
Problem with a credit reporting company's investigation into an existing problem     511
Struggling to pay mortgage                                                           510
Fees or interest                                                                     483
Deposits and withdrawals                                                             475
Improper use of your report                                                          469
Fraud or scam                                                                        461
Getting a credit card                                                                389
Advertising and marketing, including promotional offers                              363
Opening an account                                                                   354
Billing disputes                                                                     327
Problem caused by your funds being low                                               320
Application, originator, mortgage broker                                             274
Using a debit or ATM card                                                            257
Attempts to collect debt not owed                                                    249
Managing the loan or lease                                                           246
Applying for a mortgage or refinancing an existing mortgage                          239
Problem when making payments                                                         238
Other                                                                                215
Problems caused by my funds being low                                                208
Making/receiving payments, sending money                                             189
Identity theft / Fraud / Embezzlement                                                180
Trouble using your card                                                              175
Closing on a mortgage                                                                172
Settlement process and costs                                                         163
Closing/Cancelling account                                                           145
Problems at the end of the loan or lease                                             134
Cont'd attempts collect debt not owed                                                131
Other transaction problem                                                            128
Advertising and marketing                                                            123
Communication tactics                                                                122
APR or interest rate                                                                 113
Took or threatened to take negative or legal action                                  105
False statements or representation                                                   103
Name: count, dtype: int64

In [44]:
df.to_csv("../data/processed/cleaned_data.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [45]:
df.to_csv("../data/processed/cleaned_data.csv", index=False)

In [46]:
clean_df = pd.read_csv("../data/processed/cleaned_data.csv")
clean_df.head()

,text,label
0,i upgraded my xxxx xxxx card in xxxx2018 and w...,"Other features, terms, or problems"
1,chase card was reported on xxxx2019 however fr...,Incorrect information on your report
2,on xxxx2018 while trying to book a xxxx xxxx t...,Incorrect information on your report
3,my grand son give me check for 160000 i deposi...,Managing an account
4,can you please remove inquiry,Improper use of your report

In [47]:
clean_df.shape

(18696, 2)

In [48]:
X = clean_df["text"]
y = clean_df["label"]

In [49]:
X.head()

0    i upgraded my xxxx xxxx card in xxxx2018 and w...
1    chase card was reported on xxxx2019 however fr...
2    on xxxx2018 while trying to book a xxxx xxxx t...
3    my grand son give me check for 160000 i deposi...
4                        can you please remove inquiry
Name: text, dtype: object

In [50]:
y.head()

0      Other features, terms, or problems
1    Incorrect information on your report
2    Incorrect information on your report
3                     Managing an account
4             Improper use of your report
Name: label, dtype: object

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [54]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((14956,), (3740,), (14956,), (3740,))

In [55]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((14956,), (3740,), (14956,), (3740,))

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [57]:
vectorizer = TfidfVectorizer(max_features=5000)

In [58]:
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [59]:
X_train_tfidf.shape

(14956, 5000)

In [60]:
X_train_tfidf.shape

(14956, 5000)

In [61]:
from sklearn.linear_model import LogisticRegression

In [62]:
model = LogisticRegression(max_iter=1000)

In [63]:
model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [64]:
y_pred = model.predict(X_test_tfidf)

In [68]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [69]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.46684491978609627

In [70]:
print(classification_report(y_test, y_pred))

                                                                                  precision    recall  f1-score   support

                                                            APR or interest rate       0.00      0.00      0.00        25
                                         Account opening, closing, or management       0.28      0.20      0.24        94
                                                       Advertising and marketing       0.00      0.00      0.00        23
                         Advertising and marketing, including promotional offers       0.60      0.51      0.55        75
                                        Application, originator, mortgage broker       0.38      0.27      0.31        49
                     Applying for a mortgage or refinancing an existing mortgage       0.67      0.51      0.58        55
                                               Attempts to collect debt not owed       0.25      0.12      0.17        40
                                                                Billing disputes       0.40      0.03      0.06        66
                                                              Closing an account       0.53      0.47      0.50       155
                                                           Closing on a mortgage       0.62      0.16      0.25        32
                                                            Closing your account       0.56      0.64      0.60       109
                                                      Closing/Cancelling account       0.00      0.00      0.00        26
                                                           Communication tactics       0.65      0.41      0.50        27
                                           Cont'd attempts collect debt not owed       0.22      0.18      0.20        22
                                                        Deposits and withdrawals       0.37      0.12      0.18        93
                                              False statements or representation       0.00      0.00      0.00        21
                                                                Fees or interest       0.46      0.63      0.53       106
                                                                   Fraud or scam       0.71      0.59      0.65       102
                                                           Getting a credit card       0.60      0.55      0.57        82
                                           Identity theft / Fraud / Embezzlement       0.00      0.00      0.00        37
                                                     Improper use of your report       0.64      0.63      0.63        95
                                            Incorrect information on your report       0.41      0.64      0.50       238
                                        Loan modification,collection,foreclosure       0.51      0.65      0.57       109
                                        Loan servicing, payments, escrow account       0.34      0.53      0.41       123
                                        Making/receiving payments, sending money       0.00      0.00      0.00        41
                                                             Managing an account       0.40      0.79      0.53       460
                                                      Managing the loan or lease       0.35      0.32      0.33        38
                                                              Opening an account       0.57      0.34      0.43        73
                                                                           Other       0.00      0.00      0.00        51
                                              Other features, terms, or problems       0.42      0.42      0.42       159
                                                       Other transaction problem       0.20      0.04      0.07        25
                                          Problem caused by your funds being low       0.47      0.31      0.38        54
                                                    Problem when making payments       0.34      0.20      0.25        51
Problem with a credit reporting company's investigation into an existing problem       0.49      0.30      0.37       107
                    Problem with a lender or other company charging your account       0.38      0.10      0.16       116
                                 Problem with a purchase shown on your statement       0.55      0.89      0.68       328
                                        Problems at the end of the loan or lease       0.62      0.24      0.34        34
                                           Problems caused by my funds being low       0.64      0.22      0.33        41
                                                    Settlement process and costs       0.00      0.00      0.00        36
                                                      Struggling to pay mortgage       0.46      0.43      0.45        91
                             Took or threatened to take negative or legal action       1.00      0.09      0.16        23
                                                  Trouble during payment process       0.48      0.34      0.40       117
                                                         Trouble using your card       0.72      0.41      0.52        32
                                                       Using a debit or ATM card       0.75      0.05      0.10        59

                                                                        accuracy                           0.47      3740
                                                                       macro avg       0.41      0.30      0.32      3740
                                                                    weighted avg       0.45      0.47      0.42      3740

c:\Users\Ak99D\OneDrive\Desktop\Complaint Ai project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Ak99D\OneDrive\Desktop\Complaint Ai project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Ak99D\OneDrive\Desktop\Complaint Ai project\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [71]:
confusion_matrix(y_test, y_pred)

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0, 19,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ..., 40,  0,  0],
       [ 0,  0,  0, ...,  0, 13,  0],
       [ 0,  0,  0, ...,  0,  0,  3]], shape=(44, 44))

In [72]:
label_counts = clean_df["label"].value_counts()

valid_labels = label_counts[label_counts >= 300].index

clean_df = clean_df[clean_df["label"].isin(valid_labels)]

clean_df["label"].value_counts()

label
Managing an account                                                                 2269
Problem with a purchase shown on your statement                                     1802
Incorrect information on your report                                                1167
Other features, terms, or problems                                                   752
Closing an account                                                                   745
Loan servicing, payments, escrow account                                             654
Problem with a lender or other company charging your account                         584
Loan modification,collection,foreclosure                                             582
Trouble during payment process                                                       526
Closing your account                                                                 524
Account opening, closing, or management                                              520
Problem with a credit reporting company's investigation into an existing problem     511
Struggling to pay mortgage                                                           510
Fees or interest                                                                     483
Deposits and withdrawals                                                             475
Improper use of your report                                                          469
Fraud or scam                                                                        461
Getting a credit card                                                                389
Advertising and marketing, including promotional offers                              363
Opening an account                                                                   354
Billing disputes                                                                     327
Problem caused by your funds being low                                               320
Name: count, dtype: int64

In [73]:
X = clean_df["text"]
y = clean_df["label"]

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [76]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [77]:
vectorizer = TfidfVectorizer(max_features=5000)

In [78]:
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
model = LogisticRegression(max_iter=1000)

In [81]:
model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [82]:
y_pred = model.predict(X_test_tfidf)

In [83]:
from sklearn.metrics import accuracy_score

In [85]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5574712643678161

In [86]:
print("Final Model Accuracy:", accuracy)

Final Model Accuracy: 0.5574712643678161

In [87]:
print(classification_report(y_test, y_pred))

                                                                                  precision    recall  f1-score   support

                                         Account opening, closing, or management       0.39      0.17      0.24        92
                         Advertising and marketing, including promotional offers       0.76      0.48      0.59        67
                                                                Billing disputes       0.50      0.02      0.03        61
                                                              Closing an account       0.51      0.42      0.46       144
                                                            Closing your account       0.72      0.63      0.68       123
                                                        Deposits and withdrawals       0.44      0.08      0.14        97
                                                                Fees or interest       0.60      0.71      0.65        90
                                                                   Fraud or scam       0.69      0.60      0.64        88
                                                           Getting a credit card       0.58      0.42      0.49        80
                                                     Improper use of your report       0.72      0.60      0.66        95
                                            Incorrect information on your report       0.57      0.75      0.64       228
                                        Loan modification,collection,foreclosure       0.54      0.66      0.60       120
                                        Loan servicing, payments, escrow account       0.44      0.60      0.51       115
                                                             Managing an account       0.47      0.80      0.59       465
                                                              Opening an account       0.66      0.29      0.40        80
                                              Other features, terms, or problems       0.57      0.51      0.54       157
                                          Problem caused by your funds being low       0.60      0.34      0.44        61
Problem with a credit reporting company's investigation into an existing problem       0.69      0.31      0.42       101
                    Problem with a lender or other company charging your account       0.37      0.10      0.16       107
                                 Problem with a purchase shown on your statement       0.64      0.87      0.74       343
                                                      Struggling to pay mortgage       0.55      0.36      0.44       121
                                                  Trouble during payment process       0.60      0.37      0.45       123

                                                                        accuracy                           0.56      2958
                                                                       macro avg       0.57      0.46      0.48      2958
                                                                    weighted avg       0.56      0.56      0.53      2958

In [ ]:
sample_text = X_test.iloc[0]
print("Text:", sample_text)
print("Actual:", y_test.iloc[0])
print("Predicted:", model.predict(vectorizer.transform([sample_text]))[0])

In [90]:
import seaborn as sns

In [91]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

In [92]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix